### ISSUE TITLE
Static struct returns don't skip 64bit args properly (Windows)

### ISSUE THREAD

**Issue by Cvolton** [geode-sdk/TulipHook#11]
idk if this is an accurate name but whatever

While calling `GameToolbox::timestampToHumanReadable(time_t)` on Windows, the time_t argument (which is effectively a 64bit int) is supposed to be on stack (shown as `CONCAT44(in_stack_00000008,in_stack_00000004)` in Ghidra). Instead it goes somewhere else (idk where) and if I want to call the desired function, I need to change the function signature to something like `GameToolbox::timestampToHumanReadable(time_t, time_t)`. This allows me to use the function - the first argument goes unused and the second argument is then used for the actual value.

This means that instead of doing
```cpp
auto date = GameToolbox::timestampToHumanReadable(m_uploadDate);
```
I have to do something like
```cpp
auto date = GameToolbox::timestampToHumanReadable(0, m_uploadDate);
```
the function then works properly and returns the intended result

**Comment by dankmeme01** [comment]
fixed in 7fa328b76892f0f2c9f486ef2ad6aaaed5997b43
